config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :sessions
  resources :cities

  resources :gossips do
    resources :comments
  end


  get 'static_pages/contact', to: 'static_pages#contact'

  get 'static_pages/team', to: 'static_pages#team'

  get 'welcome/:id', to: 'welcome#welcome_page'

  get 'bonjour/:id', to: 'welcome#bonjour_page'

  get 'users/:id', to: 'users#show'

  root 'home_page#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users

 #critères de validation
   validates :zip_code,
	    presence: true,
	    uniqueness: true,
	    length: { is: 5 },
	    format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
   validates :name,
	    presence: true,
	    length: { in: 3..30 }
end

app/models/comment.rb
class Comment < ApplicationRecord


  belongs_to :user
  belongs_to :gossip


 #critères de validation
    validates :content,
	    presence: true ,
	    length: { in: 4..800 }
	    

end

app/models/gossip.rb
class Gossip < ApplicationRecord


  belongs_to :user
  has_many :tag_gossip_links
  has_many :tags, through: :tag_gossip_links
  has_many :comment


 #critères de validation
   validates :title,
	    presence: true ,
	    length: { in: 4..14 }
	validates :content, presence: true

end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :recipient_to_pm_links, foreign_key: 'received_message_id'
  has_many :recipients, foreign_key: 'recipient_id', class_name: "User", through: :recipient_to_pm_links
end

app/models/recipient_to_pm_link.rb
class RecipientToPmLink < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :received_message, class_name: "PrivateMessage"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_gossip_links
  has_many :gossips, through: :tag_gossip_links

 #critères de validation
   validates :title,
	    presence: true,
	    length: { in: 3..30 }
end

app/models/tag_gossip_link.rb
class TagGossipLink < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :recipient_to_pm_links, foreign_key: 'recipient_id'
  has_many :received_messages, foreign_key: 'received_message_id', class_name: "PrivateMessage", through: :recipient_to_pm_links
  has_many :comment
  
#critères de validation
   validates :first_name,
	    presence: true,
	    length: { in: 3..50 }
   validates :last_name,
	    presence: true,
	    length: { in: 3..50 }
   validates :email,
	    presence: true,
   		uniqueness: true,
    	format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 include SessionsHelper

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

	def show
		@city = City.find(params[:id])
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


	def edit
		@comment = Comment.find(params[:id])
	end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

 before_action :authenticate_user, only: [:create, :new, :edit, :destroy]
 before_action :is_author?, only: [:edit, :update, :destroy]

	def show
		@gossip = Gossip.find(params[:id])
	end

	def new

	end

	def create
		@gossip = Gossip.new(title: params[:title], content: params[:content], user_id: session[:user_id])
		#avec xxx qui sont les données obtenues à partir du formulaire

		if @gossip.save # essaie de sauvegarder en base @gossip
		    # si ça marche, il redirige vers la page d'index du site

		    flash[:notice] = "Votre gossip a bien été ajouté"
		    redirect_to root_path(success: true)
   			else
    		# sinon, il render la view new (qui est celle sur laquelle on est déjà)
		    flash[:notice] = "Erreur dans la création, merci de remplir les champs demandés"

			render 'new'
		end
	end


	def edit
		@gossip = Gossip.find(params[:id])
	end

	def update
		@gossip = Gossip.find(params[:id])
		gossip_params = params.require(:gossip).permit(:title,:content)

	  if @gossip.update(gossip_params)

	    redirect_to root_path
	  else
	    flash[:notice] = "Votre gossip n'a pas été modifié correctement, veuillez recommercer !"
	   
	    redirect_to edit_gossip_path
	  end
	end

	def destroy
	
		@gossip = Gossip.find(params[:id])

	  if @gossip.destroy

	    redirect_to root_path
	  else
	    flash[:notice] = "Votre gossip n'a pas été supprimé correctement, veuillez recommercer !"
	   
	    redirect_to edit_gossip_path
	  end
	end

end

private

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index

  	@gossip = Gossip.all

  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


	def new

	end

	def create
 	 # cherche s'il existe un utilisateur en base avec l’e-mail
	  user = User.find_by(email: params[:email])

	  # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
	  if user && user.authenticate(params[:password])
	    session[:user_id] = user.id		    
	    flash[:notice] = "Vous êtes connecté !"

	    redirect_to root_path

 		else
	    flash.now[:danger] = 'Votre mot de passe et/ou email ne sont pas bon.'
    	render 'new'
  	  end
	end


	def destroy
	  session.delete(:user_id)
	  	    redirect_to root_path

	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   
	def show
		@user = User.find(params[:id])
	end

	def create

		
		#avec xxx qui sont les données obtenues à partir du formulaire

		if $city_test = City.find_by(name: params[:city])

			user_save

		else

				@city = City.new(name: params[:city], zip_code: params[:zip_code] )

				if @city.save
				    flash[:notice] = "Votre ville a été créé "
					user_save	    

		   			else
		    		# sinon, il render la view new (qui est celle sur laquelle on est déjà)
				    flash[:notice] = "Erreur dans la création, merci de remplir les champs demandés"

					render 'new'
				end


		end
	end


end


private

	def user_save
			@user = User.new(first_name: params[:first_name], last_name: params[:last_name], email: params[:email], password: params[:password], city: City.find($city_test.id) )

			if @user.save
				
			    flash[:notice] = "Vous avez bien été créé... bienvenue chez nous !"
			    redirect_to root_path(success: true)

	   			else
	    		# sinon, il render la view new (qui est celle sur laquelle on est déjà)
			    flash[:notice] = "Erreur dans la création, merci de remplir les champs demandés"

				render 'new'
			end
	end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def welcome_page

		@user = User.find(params[:id])


	end
	def bonjour_page

		@user = params[:id]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper


def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper


   def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

def authenticate_user
    unless current_user
      flash[:notice] = "Merci de vous connecter! "
      redirect_to new_session_path
    end
  end

    def is_author?
    unless current_user.id == params[:id]
      flash[:notice] = "Tu n'es pas l'auteur de ce potin."
      redirect_to root_path
    end
end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/detail/auteur.html.erb
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title@gossip Project by lyon's team - Baptiste, léo & Lionel</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="css/full-width-pics.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->

  <!-- Header - set the background image for the header in the line below -->
  <header class="py-5 bg-image-full" style="background-image: url('https://unsplash.it/1900/1080?image=1076');">
    <img class="img-fluid d-block mx-auto" src="http://www.lioforest.com/images/logo_potin.jpg" alt="">
  </header>

  <!-- Content section -->
  <section class="py-5">


    <div class="container">
      <h1>Auteur : <%=@user.first_name %> <%=@user.last_name %> </h1>

<br><br>
        <div>
            <div class="alert alert-dark alert-dismissible fade show" role="alert">
              Identifiant N° : <%=@user.id %><br>

             <hr>
            Détail : <%=@user.description %> 
            <br>
            <br>
            E-mail : <%=@user.email %> 
            <br>
            <br>
            Age :    <%=@user.age %> 
            <br>
            <br>
            Ville :  <%=@user.city.name %> 
            <br>
            </div>
          <p><br><br> </p>
        </div>
    </div>
  </section>


  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Lioforest/thp 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Gossip Project</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="<%=root_path%>">Accueil
              <span class="sr-only">(current)</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="<%=static_pages_team_path%>">Team</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=static_pages_contact_path%>">Contact</a>
          </li>

<!-- Partie liée à la session -->
        <% unless session[:user_id]  %>
         <li class="nav-item">
           <a class="nav-link" href="<%= new_user_path %>">S'inscrire</a>
         </li>

         <li class="nav-item">
           <a class="nav-link" href="<%= new_session_path %>">Se connecter</a>
         </li>
         <% else%>
         <li>
           <a href="<%= session_path(session[:user_id]) %>" class="nav-link" data-method= "delete">Se deconnecter</a>
         </li>
         <% end %> 
        </ul>
      </div>
    </div>
  </nav>
<div><%= flash[:notice] %></div>

  <%= yield %>
  </body>
</html>